### ISSUE TITLE
Error message downloading pdf presentation?

### ISSUE THREAD

**Issue by SandMT** [spsrc/reproducibility-course#6]
Al intentar descargar el pdf de la primera charla de Susana me ha salido este error
![image](https://user-images.githubusercontent.com/102554372/161431351-5df75efb-6792-460f-95ea-e1a874f5ad94.png)
Ya tengo el PDF.... pero aprovecho y practico el crear un issue ;-)
Gracias !

**Comment by manuparra** [comment]
Muchas gracias  @SandMT  ! 
@jmoldon Puedes cerrar este issue ya que ha sido resuelto.
Saludos.

**Comment by jmoldon** [comment]
Gracias @SandMT, yo lo he visto bien, y veo que ya te funciona también. Supongo que no se renderizó bien en un momento particular, algunas veces ocurre.

Bien por cerrar el issue una vez solucionado el problema. Por cierto, como demuestra este mensaje, los comentarios pueden seguir aunque se cierre un issue.
